# PyTorch

PyTorch is an open source optimized tensor library for deep learning using GPUs and CPUs. It is a deep learning framework that provides a whole stack to preprocess data, model data and deploy the models in cloud. PyTorch leverages <b>CUDA</b> (Compute Unified Device Architecture) which is an API (Application Programming Interface) developed by Nvidia for general computing on GPUs (Graphical Processing Units). This enables us to accelerate the modelling process due to faster computations because CUDA enables us to run the computations on GPU (if available).

In [7]:
import torch
import numpy as np
torch.__version__

'2.7.0'

## What is a Tensor?

Tensors are simply arrays that are used to represent data similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

A scalar is a single number, and in tensor terms it is a zero dimension tensor.

In [8]:
scalar = torch.tensor(1)
scalar

tensor(1)

Dimensions of a tensor

In [9]:
scalar.ndim

0

Converting a tensor to a python number

In [10]:
scalar.item()

1

A vector is a single dimension tensor

In [11]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

A matrix is a 2 dimensional tensor.

In [14]:
# Matrix
M = torch.tensor([[7, 8],
                [9, 10]])
M

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
M.ndim

2

Creation of a tensor

In [17]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [61]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [24]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7033, 0.0072, 0.0208, 0.3163],
        [0.7173, 0.9197, 0.2152, 0.3863],
        [0.9060, 0.1341, 0.1837, 0.0620]])

Random tensor with similar shape to an image tensor. $1^{st}$ dimension is the color channels, $2^{nd}$ dimension is the height and $3^{rd}$ dimension is the width.

In [25]:
rand_image_tensor = torch.rand(size = (3,224,224))
rand_image_tensor

tensor([[[4.6252e-01, 6.8493e-01, 9.2644e-01,  ..., 8.3281e-01,
          7.5196e-01, 7.8708e-01],
         [7.8042e-01, 3.9105e-01, 5.7301e-01,  ..., 4.3212e-01,
          8.2964e-01, 4.6402e-02],
         [5.8364e-01, 7.7383e-01, 3.3439e-02,  ..., 9.6866e-01,
          1.3825e-02, 2.1600e-02],
         ...,
         [3.3342e-01, 7.2911e-01, 8.7512e-01,  ..., 7.0167e-01,
          5.9874e-02, 9.1148e-01],
         [6.6047e-01, 4.3686e-02, 1.5338e-01,  ..., 1.2216e-01,
          8.4989e-01, 6.1421e-02],
         [3.1999e-01, 7.4338e-01, 9.2654e-01,  ..., 5.8881e-01,
          3.0616e-01, 7.7568e-01]],

        [[7.2034e-01, 6.9610e-01, 5.9102e-01,  ..., 9.2958e-01,
          1.6569e-01, 1.7074e-01],
         [9.6824e-01, 4.8632e-02, 4.4943e-02,  ..., 6.4951e-01,
          6.9099e-02, 1.9791e-01],
         [9.3951e-01, 8.1072e-02, 7.9214e-01,  ..., 3.6702e-01,
          2.4208e-01, 6.9468e-01],
         ...,
         [1.8619e-01, 3.4491e-01, 9.5325e-01,  ..., 4.5718e-01,
          5.484

Zeros and ones

In [26]:
zero_tensor = torch.zeros(size = (3,4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
one_tensor = torch.ones(size = (3,4))
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Default datatype in pytorch is float32

In [29]:
one_tensor.dtype

torch.float32

Creating a range of tensors and tensors-like

In [30]:
range_tensor = torch.arange(0,10)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# creating tensors-like
torch.zeros_like(range_tensor)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Three most important parmeters when creating tensors are <b>dtype, device</b> and <b>requires_grad</b>.

1. Some datatypes are specific for GPUs and some are specific for CPUs. Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).
The different types of bits for datatype has to do with the precision of the value. The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.
This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.
So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

2. The argument device refers to what device the tensor is saved on. If one of your tensors is on the CPU and the other is on the GPU, you get an error when you perform a computation on them.

3. requires_grad refers to whether or not to track gradients with the tensor operations

In [36]:
x_tensor = torch.tensor([1.0,2.0,3.0],
             dtype = torch.float32,
             device = 'cpu',
             requires_grad=False,)
print('Datatype of the tensor is ',x_tensor.dtype)
print('Device the tensor is save on is ',x_tensor.device)

Datatype of the tensor is  torch.float32
Device the tensor is save on is  cpu


In [37]:
# converting dtype of a tensor
x16_tensor = x_tensor.type(torch.float16)
x16_tensor.dtype

torch.float16

## Basic operations

In [38]:
# element wise multiplication
torch.mul(x16_tensor,10)
x16_tensor * 10

tensor([10., 20., 30.], dtype=torch.float16)

In [39]:
torch.subtract(x16_tensor,2)
x16_tensor - 2

tensor([-1.,  0.,  1.], dtype=torch.float16)

In [40]:
torch.add(x16_tensor,3)
x16_tensor + 3

tensor([4., 5., 6.], dtype=torch.float16)

In [41]:
torch.divide(x16_tensor,2)
x16_tensor/2

tensor([0.5000, 1.0000, 1.5000], dtype=torch.float16)

In [43]:
rand_tensor = torch.rand(size = (3,3))
# you can use @ to perform matrix multiplication
rand_tensor @ rand_tensor
# you can use the predefined method
torch.matmul(rand_tensor,rand_tensor)
# mm is short form of matmul
torch.mm(rand_tensor,rand_tensor)

tensor([[1.1568, 0.9598, 1.6082],
        [1.3775, 1.4593, 1.5127],
        [1.1015, 1.6211, 1.3316]])

There are several other functions and methods which are more or less similar to the ones on numpy.

In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix.

In [52]:
rand_tensor.add_(5)
rand_tensor

tensor([[5.0531, 5.3376, 5.2132],
        [5.3989, 5.6977, 5.5037],
        [5.8739, 5.3917, 5.2995]])

## PyTorch and NumPy

Transform numpy array to pytorch tensor

In [45]:
arr = np.arange(1.0,10.0)
arr_tensor = torch.from_numpy(arr)
arr, arr_tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [46]:
arr.dtype, arr_tensor.dtype

(dtype('float64'), torch.float64)

Tensor to numpy array

In [47]:
tensor_numpy = arr_tensor.numpy()
tensor_numpy

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
tensor_numpy.dtype

dtype('float64')

Setting a random seed. When using a jupyter notebook, you shall set random seed everytime you use random.

In [49]:
torch.manual_seed(42)

## Accessing a GPU

In [50]:
# configuration of the GPU
!nvidia-smi

zsh:1: command not found: nvidia-smi


Check for GPU access

In [53]:
# if False it means GPU is not available
torch.cuda.is_available()

False

Its not likely that you always have access to a GPU. So we can set a device agnostic code as below

In [83]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [84]:
# count number of devices
torch.cuda.device_count()

0

Since I am using a mac, I can check what type of accelerator I have.

In [60]:
if torch.accelerator.is_available():
    device = torch.accelerator.current_accelerator()
    print(device)

mps


MPS in the context of PyTorch refers to the Metal Performance Shaders backend.

* **Metal:** This is Apple's proprietary API (Application Programming Interface) for programming their GPUs (Graphics Processing Units). It provides low-level access to the graphics hardware for maximum performance in graphics rendering and parallel computations.
* **Metal Performance Shaders (MPS):** This is a framework built on top of Metal. It's a collection of highly optimized compute and graphics shaders specifically designed to integrate into applications using the Metal API. These shaders are fine-tuned for the unique characteristics of Apple's GPUs (found in Apple Silicon and some older AMD-based Macs).
* **MPS Backend in PyTorch:** PyTorch has integrated MPS as a backend, allowing you to run tensor computations and train neural networks on Apple GPUs. By moving your PyTorch tensors and models to an "mps" device (e.g., `torch.device("mps")`), you can leverage the power of the Apple GPU for significantly faster computations compared to running on the CPU.

**Key benefits of using the MPS backend in PyTorch:**

* **Accelerated Training and Inference:** Utilizing the GPU's parallel processing capabilities can drastically reduce the time required for training complex models and performing inference.
* **Optimized Performance:** MPS is specifically designed for Apple's hardware, meaning the operations are highly optimized for their architecture.
* **Ease of Use:** PyTorch's integration allows you to switch to GPU computation with minimal code changes, similar to using CUDA on NVIDIA GPUs.

**In summary, MPS in PyTorch enables high-performance training and inference on Apple Silicon and compatible AMD GPUs by utilizing Apple's Metal Performance Shaders framework.**

### Putting Tensors and Models on the GPUs

In [62]:
cpu_tensor = torch.tensor([1,2,3], device=device)
cpu_tensor.device

device(type='mps', index=0)

In [63]:
# use 'to' to change the device. incase of GPU availability it shows cuda with the index of the GPU used
cpu_tensor.to(device)
cpu_tensor

tensor([1, 2, 3], device='mps:0')

To convert a tensor on GPU to numpy is not possible. The device has to be changed to CPU and then converted to numpy array.

In [64]:
cpu_tensor.cpu().numpy()

array([1, 2, 3])

## Preparing and converting dataset

The <b>nn</b> module of torch provides all the building blocks for neural networks.

In [88]:
from torch import nn

In [89]:
# subclass the nn.module class that contains all the building blocks required
class LinearRegression(nn.Module):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.weights = nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
        self.bias = nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))

    def forward(self,x: torch.Tensor):
        return x*self.weights + self.bias

In [90]:
torch.manual_seed(42)
la = LinearRegression()
list(la.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [91]:
# list of named parameters
la.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])